# WIP

distributable:
  url: https://github.com/FuelLabs/sway/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

provides:
  - bin/forc

versions:
  - 0.31.1

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script:
    cd sway
    cargo build

test:
  cargo run --bin forc -- --help
