distributable:
  url: https://download.redis.io/releases/redis-{{ version }}.tar.gz
  strip-components: 1

versions:
  github: redis/redis


provides:
  - bin/redis-server
  # - etc/redis.conf

dependencies:
  openssl.org: ^1

build:
  dependencies:
    gnu.org/make: '>=4.3'
    freedesktop.org/pkg-config: '>=0.29'
  script:
    PREFIX={{prefix}}
    BUILD_TLS=yes
    make install
    # todo:
    #   where to put redis.conf ? .tea/redis.io/etc?

    # %w[run db/redis log].each { |p| (var/p).mkpath }

    # # Fix up default conf file to match our paths
    # inreplace "redis.conf" do |s|
    #   s.gsub! "/var/run/redis.pid", var/"run/redis.pid"
    #   s.gsub! "dir ./", "dir #{var}/db/redis/"
    #   s.sub!(/^bind .*$/, "bind 127.0.0.1 ::1")
    # end

    # etc.install "redis.conf"
    # etc.install "sentinel.conf" => "redis-sentinel.conf"
test:
  script: |
    redis-server --test-memory 2
  # %w[run db/redis log].each { |p| assert_predicate var/p, :exist?, "#{var/p} doesn't exist!" }