distributable:
  url: https://github.com/FuelLabs/fuel-core/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

provides:
  - bin/fuel-core

versions:
  - 0.14.1

build:
  dependencies:
    rust-lang.org: ^1.47.0
    rust-lang.org/cargo: ^0.65
  script:
    cargo xtask build --path=. --root={{prefix}}
  test:
    cargo test

test:
  fuel-core run --help
