distributable:
  url: https://ziglang.org/download/{{version}}/zig-{{version}}.tar.xz
  strip-components: 1

versions:
  github: ziglang/zig/tags

build:
  dependencies:
    cmake.org: '>=2.8.12'
    llvm.org: ^15 # v0.10.0
    tea.xyz/gx/cc: '*'
    tea.xyz/gx/make: '*'
    git-scm.org: '*'
    invisible-island.net/ncurses: 6

  script: |
    # https://github.com/ziglang/zig/issues/13388
    git apply props/build.diff

    mkdir build
    cd build
    cmake .. $ARGS
    make install
  env:
    ARGS:
      - -DCMAKE_INSTALL_PREFIX="{{prefix}}"
      - -DCMAKE_BUILD_TYPE=Release
      - -DZIG_STATIC_LLVM=ON
    linux:
      ARGS:
        - -DCMAKE_EXE_LINKER_FLAGS="-Wl,--reduce-memory-overheads -Wl,--hash-size=1021"

test:
  script: |
    cp $FIXTURE hello.zig
    zig build-exe hello.zig
    ./hello
  fixture: |
      const std = @import("std");
      pub fn main() !void {
          const stdout = std.io.getStdOut().writer();
          try stdout.print("Hello, world!", .{});
      }

provides:
  - bin/zig
