distributable:
  url: https://github.com/FuelLabs/sway/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  - 0.31.1

provides:
  - bin/forc

build:
  dependencies:
    rust-lang.org: ^1.47.0
    rust-lang.org/cargo: ^0.65
  script:
    cargo install --path=sway --root={{prefix}}
  test:
    cargo test

test:
  script: |
    cargo run --bin forc -- --help