distributable:
  url: https://github.com/FuelLabs/sway/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: FuelLabs/sway

provides:
  - bin/forc

build:
  dependencies:
    rust-lang.org: 1
    rust-lang.org/cargo: ^0.65
  script:
    cargo install forc

test:
  script: |
    forc --help
