distributable:
  url: https://codeload.github.com/rustls/rustls-ffi/tar.gz/refs/tags/v{{version}}
  strip-components: 1

versions:
  github: rustls/rustls-ffi/tags
  strip: /v/

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    rust-lang.org/cargo: '*'
  script: |
    cargo install cbindgen
    make DESTDIR={{prefix}}
    make DESTDIR={{prefix}} install

test:
  script: true

